version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/php:8.0.15-browsers
    steps:
      - checkout
      - run: php --version
      
# Orchestrate our job run sequence
workflows:
  test_and_deploy:
    jobs:
      - test


      # install composer depen
    
